#!/bin/bash
# Regenerate docs/MAPPING.md from packages/*.map. Usage: test/gen-mapping-doc.sh
set -euo pipefail
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

out=docs/MAPPING.md
{
  echo "# Package mapping"
  echo
  echo "Generated by \`test/gen-mapping-doc.sh\` — do not edit by hand."
  echo
  echo "Strategies: \`apt\` (direct), \`apt-any\` (first available of a list),"
  echo "\`apt-hw\` (only when matching hardware detected), \`external\` (installer"
  echo "function in install/20-external.sh), \`manual\`, \`skip\`."
  for map in packages/base.map packages/extra.map; do
    title=${map##*/}
    echo
    echo "## \`$title\`"
    echo
    echo "| Upstream (Arch) | Strategy | Debian target / note |"
    echo "|---|---|---|"
    while IFS=$'\t' read -r pkg strategy arg notes; do
      [[ -z $pkg || $pkg == \#* ]] && continue
      target=$arg
      [[ -z $target ]] && target="—"
      [[ -n $notes ]] && target="$target — $notes"
      printf '| `%s` | `%s` | %s |\n' "$pkg" "$strategy" "$target"
    done <"$map"
  done
} >"$out"
echo "wrote $out"
